version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.serve.api:app --host 0.0.0.0 --port 8000

  ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run ui/app.py

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.1
    ports:
      - "5001:5000"
    environment:
      - MLFLOW_TRACKING_URI=/mlruns
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri /mlruns --host 0.0.0.0 --port 5000
